<?php
    define("DB_DSN", "mysql:host=localhost;dbname=dbaprendefacil" );
    define("DB_USUARIO", "root" );
    define('DB_CONTRASENA', '');
    define('TABLA_ALUMNOS', 'alumnos');
    define('TABLA_PROFESORES', 'profesores');
    define('TABLA_TAREAS', 'tareas');
    define('TABLA_PASOS', 'pasos');
    define('TABLA_MULTIMEDIA', 'multimedia');
    define('TABLA_TAREA_ALUMNO', 'tarea_alumno');
    define('TABLA_CONTRASEÑA_PICTOGRAMA', 'password_pictograma');
    define('TABLA_PICTOGRAMAS', 'pictogramas');
?>